### PR TITLE
Added BigDecimal inline array property

### LINKED ISSUE #380: Add BigDecimal inline array property type
Can only be done when #230 is closed: introduce an inline array property type constant for the type `BigDecimal`. It should behave like the other number types.

## To do
- Add a BIG_DECIMAL constant for the BigDecimal number type (between Double and String)
- Adapt tests

### PR DESCRIPTION
**Pull request by Akshayp02**
this Pr fixes #380 i have Added BigDecimal inline array property and updated tow files with test cases.

### CODE REVIEW

**Comment by ljacqu** [comment]
Hi @Akshayp02, thanks for your interest in ConfigMe! Unfortunately, this PR does not match the requirements of the issue, and the code doesn't compile. I recommend taking some time to further familiarize yourself with Java before contributing to other projects.

I appreciate your interest, and I encourage you to keep practicing and learning. With continued effort, I'm sure you'll be able to make meaningful contributions to open-source projects in the future.

Best of luck with your coding journey!

**Comment by Akshayp02** [comment]
I sincerely apologize for any inconvenience, ma'am. Would it be possible to grant me another opportunity to work on it? I'm well-versed in the concept of BigDecimal in Java, but since I'm new to this rather extensive codebase, I initially encountered some confusion. I assure you that with this chance, I will be able to contribute effectively and efficiently.

**Comment by ljacqu** [comment]
No apologies needed! If you want to give it another go, that's fine by me, but as mentioned, I think it might be a bit too early :smile:

**Comment by Akshayp02** [comment]
Thank you very much, ma'am! ❤️ Actually, ma'am, I have my academic exams for the next 3-4 days, so I kindly request some time for that.

**Pull request closed without merging**
