### PR TITLE
Resolution of issue #71

### PR DESCRIPTION
**Pull request by ZENEGIX**

### CODE REVIEW

**Comment by ljacqu** [comment]
Would it not be better to fix the map after reading it, just once? Otherwise in the future other methods using the internal `root` Map will fail.
Other question is whether SnakeYAML can be configured to produce a regular Map. I tried a quick Google search but it's kind of hard to find the proper keywords to find relevant results.

**Comment by ZENEGIX** [comment]
You want from this:
```yaml
commands:
    authme.register:
        description: 'Register a player'
```
Do it?
```yaml
commands:
    authme:
        register:
            description: 'Register a player'
```

**Comment by ljacqu** [comment]
Yes. 

Personally I would add a method like `sanitizeMap(Map)` to the YamlFileReader which gets called at the end of `loadFile`. This would allow the behavior to be overridden. So this:
```java
        try (FileInputStream fis = new FileInputStream(file);
             InputStreamReader isr = new InputStreamReader(fis, charset)) {
            Object obj = new Yaml().load(isr);
            return obj == null ? Collections.emptyMap() : (Map<String, Object>) obj;
        }
```

would become
```java
        try (FileInputStream fis = new FileInputStream(file);
             InputStreamReader isr = new InputStreamReader(fis, charset)) {
            Object obj = new Yaml().load(isr);
            return sanitizeMap((Map<String, Object>) obj);
        }
 }

protected Map<String, Object> sanitizeMap(Map<String, Object> object) {
  if (object == null) {
     return Collections.emptyMap();
  }
  // etc.
}
```

Background: I did some reading and it seems like the YAML standard doesn't really work like that, but somehow we need to be able to concatenate paths and the period is just a natural way of doing it. As such, I find it's OK to deviate from the standard so we have consistent behavior. Spring and Bukkit's FileConfiguration behave like that, too.

**Comment by ljacqu** [comment]
Thank you ;)

**Pull request merged**
